services:
    _defaults:
        autowire: true

    Kutny\CronBundle\CronCommandManager:

    Kutny\CronBundle\CronDebuggerCommand:
        arguments:
            - '@service_container'
        tags:
            - {name: console.command}

    Kutny\CronBundle\CronRunnerCommand:
        arguments:
            - %kernel.environment%
            - %kernel.root_dir%/..
            - '@service_container'
        tags:
            - {name: console.command}
